global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  # Removed redundant nginx-cache-exporters - cache-metrics-exporter provides all cache stats

  - job_name: nginx-lb
    metrics_path: /metrics
    static_configs:
      - targets: []
  
  - job_name: cache-disk-metrics
    scrape_interval: 30s
    static_configs:
      - targets: ["cache-metrics-exporter:9199"]

  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets: ["172.17.0.1:9100"]

